# Catppuccin Mocha (pink accent)
background       = 0xFF1E1E2E
base             = 0xFF313244
text             = 0xFFCDD6F4
alternate_base   = 0xFF45475A
bright_text      = 0xFFF5E0DC
accent           = 0xFFF5C2E7
accent_secondary = 0xFFCBA6F7

font_family           = Noto Sans
font_family_monospace = monospace
font_size             = 11
small_font_size       = 10

rounding_large = 10
rounding_small = 5
