hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
    hl.exec_cmd("systemctl --user start mpd.service")
    hl.exec_cmd("~/.config/scripts/desktop-ui.sh")
    hl.exec_cmd("fcitx5 -d --replace")
    hl.exec_cmd("fcitx5-remote -r")
    hl.exec_cmd("~/.config/hypr/xdg-desktop-portal-hyprland.sh")
end)
