# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
# windowrule = pseudo,fcitx
# windowrulev2 = opacity 0.94 0.94,class:^(Code|Slack|WebCord|Spotify)$
# windowrulev2 = opacity 0.94 0.94,class:^(kitty)$,title:^(kitty)$
# windowrule = opacity 0.94 0.94, match:class ^(kitty)$, match:title ^(kitty)$
windowrule = opacity 0.96 0.96, match:class kitty
windowrule = match:class fcitx, pseudo on

windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^(Code|Slack|WebCord|Spotify)$, opacity 0.94 0.94
windowrule = match:class ^(kitty)$, match:title ^(kitty)$, opacity 0.94 0.94
