#!/usr/bin/env bash
# apply-theme.sh — Apply a theme across all desktop components.
#
# Two modes:
#   apply-theme.sh <theme-name>     — use a preset theme (from ~/.config/themes/)
#   apply-theme.sh --wallpaper <img> — generate theme from wallpaper via matugen
#
# Preset themes can optionally include a wallpaper path; if set, awww + matugen
# will both be triggered. If the preset only wants fixed colors (no matugen),
# it can set MATUGEN=false in its colors.sh.

set -euo pipefail

THEME_DIR="${THEME_DIR:-$HOME/.config/themes}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MATUGEN_MODE="${MATUGEN_MODE:-dark}"

# -----------------------------------------------------------
# Mode: wallpaper-based (matugen generates everything)
# -----------------------------------------------------------
if [[ "${1:-}" == "--wallpaper" ]]; then
    img="${2:-}"
    if [[ -z "$img" || ! -f "$img" ]]; then
        echo "Usage: apply-theme.sh --wallpaper <image-path>" >&2
        exit 1
    fi

    "$SCRIPT_DIR/wallpaper.sh" "$img"
    notify-send "Theme Applied" "Generated Material You colors from wallpaper"
    exit 0
fi

# -----------------------------------------------------------
# Mode: preset theme
# -----------------------------------------------------------
THEME_NAME="${1:-}"

if [[ -z "$THEME_NAME" ]]; then
    echo "Usage: apply-theme.sh <theme-name> | --wallpaper <img>" >&2
    exit 1
fi

THEME_PATH="$THEME_DIR/$THEME_NAME"

if [[ ! -d "$THEME_PATH" ]]; then
    notify-send -u critical "Theme Error" "Theme '$THEME_NAME' not found"
    exit 1
fi

if [[ ! -f "$THEME_PATH/colors.sh" ]]; then
    notify-send -u critical "Theme Error" "Missing colors.sh in '$THEME_NAME'"
    exit 1
fi

# shellcheck source=/dev/null
source "$THEME_PATH/colors.sh"

# If the preset has a wallpaper, use matugen to generate colors from it
if [[ -n "${WALLPAPER:-}" && -f "${WALLPAPER:-}" ]]; then
    "$SCRIPT_DIR/wallpaper.sh" "$WALLPAPER"
    notify-send "Theme Applied" "Switched to: ${THEME_DISPLAY_NAME:-$THEME_NAME}"
    exit 0
fi

# Otherwise, apply fixed colors manually (fallback for presets without wallpaper)

# --- Waybar ---
cat > "$HOME/.config/waybar/colors.css" <<EOF
/* Generated by apply-theme.sh for preset: $THEME_NAME */
@define-color primary ${ACCENT};
@define-color on_primary ${BG};
@define-color secondary ${ACCENT_ALT};
@define-color background ${BG};
@define-color on_background ${FG};
@define-color surface ${SURFACE0};
@define-color on_surface ${FG};
@define-color surface_variant ${SURFACE1};
@define-color on_surface_variant ${FG_DIM};
@define-color surface_container ${SURFACE0};
@define-color surface_container_high ${SURFACE1};
@define-color surface_container_highest ${SURFACE2};
@define-color outline ${SURFACE2};
@define-color outline_variant ${SURFACE1};
@define-color error ${RED};
@define-color on_error ${BG};
EOF

pkill waybar 2>/dev/null || true
sleep 0.3
"$HOME/.config/hypr/waybar.sh" &

# --- Hyprland border ---
hyprctl keyword general:col.active_border "$HYPR_ACTIVE_BORDER" 2>/dev/null || true
hyprctl keyword general:col.inactive_border "$HYPR_INACTIVE_BORDER" 2>/dev/null || true

# --- Kitty ---
if [[ -n "${KITTY_THEME:-}" ]]; then
    local_kitty_conf="$HOME/.config/kitty/kitty.conf"
    if [[ -f "$local_kitty_conf" ]]; then
        sed -i "s|^include kitty/themes/.*|include $KITTY_THEME|" "$local_kitty_conf"
        sed -i "s|^include matugen-colors.conf|# include matugen-colors.conf|" "$local_kitty_conf"
        pkill -USR1 kitty 2>/dev/null || true
    fi
fi

# --- SwayNC ---
swaync-client --reload-css 2>/dev/null || true

# --- GTK ---
if [[ -n "${GTK_THEME:-}" ]]; then
    hyprctl keyword env "GTK_THEME,$GTK_THEME" 2>/dev/null || true
fi

# --- Save ---
echo "$THEME_NAME" > "$HOME/.config/current-theme"

notify-send "Theme Applied" "Switched to: ${THEME_DISPLAY_NAME:-$THEME_NAME}"
